![imagen](./img/ejercicios.png)

# INFORMACIÓN DEL PROYECTO

### TÍTULO

## Representación femenina en los videojuegos

In [ ]:
#Escribe el título del proyecto en Markdown
titulo = ""

### TEMA

Estudio sobre la aparición de personajes de género femenino en los videojuegos entre 2012 y 2022 y sus consecuencias en estos.

In [ ]:
# Describe brevemente el tema del proyecto en Markdown
tema = ""

### HIPÓTESIS

Define aquí lo que será la hipótesis de tu proyecto.
Deberás tener más de una, pero tu proyecto lo harás teniendo una principal hipótesis.

Hipótesis principal: 
- ¿Los juegos con protagonistas femeninas bien representadas tienden a vender más o a ser más populares que aquellos con protagonistas masculinos?

Hipótesis extra:
- Hipótesis 1: La mayoría de los personajes femeninos en los videojuegos son representados como no jugables y/o tienen roles secundarios en la trama.
- Hipótesis 2: Existe una tendencia a sexualizar a los personajes femeninos en los videojuegos, especialmente en aquellos en los que son jugables.
- Hipótesis 3: Los personajes femeninos tienden a ser representados en roles de interés romántico o como damiselas en apuros, en lugar de protagonistas o personajes principales.
- Hipótesis 4: Hay una correlación entre la sexualización de los personajes femeninos y su relevancia en la trama del juego.
- Hipótesis 5: ¿Los juegos con una representación de género más equitativa tienden a recibir puntuaciones más altas?
- hipótesis 6:  ¿Hay alguna tendencia discernible en cuanto a la representación de género y su impacto en la recepción del juego?

In [ ]:
# Escribe tu hipótesis principal en Markdown
hipotesis_1 = ""

Otras hipótesis:
- Los juegos con protagonistas femeninas han aumentado en los últimos años, pero siguen estando en minoría con respecto a los juegos con protagonistas o personajes masculinos.

In [ ]:
# Escribe más hipótesis si las hubiera en Markdown
# hipotesis_2 = ""
# hipotesis_3 = ""
# hipotesis_4 = ""
# hipotesis_5 = ""
# ...

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [4]:
import pandas as pd

# guarda en variables los datasets y su fuente
df_1 = pd.read_csv("./data/characters.grivg.csv")
fuente_1 = "https://www.kaggle.com/datasets/br33sa/gender-representation-in-video-games"

df_2 = pd.read_csv("./data/games.grivg.csv")
fuente_2 = "https://www.kaggle.com/datasets/br33sa/gender-representation-in-video-games"

df_3 = pd.read_csv("./data/sexualization.grivg.csv")
fuente_3 = "https://www.kaggle.com/datasets/br33sa/gender-representation-in-video-games"

# df_4 = pd.DataFrame()
# fuente_4 = ""
# df_5 = pd.DataFrame()
# fuente_5 = ""
# ...

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [7]:
# Primer dataset
df_1.head()

,Name,Gender,Game,Age,Age_range,Playable,Sexualization,Id,Species,Side,Relevance,Romantic_Interest
0,Farah,Female,CODMW,27,Adult,1,0,CODMW_Farah,Human,P,PA,No
1,Protagonist,Custom,PSS,Teenager,Teenager,1,0,PSS_Protagonist,Human,P,PA,No
2,Magnolia,Female,PSS,Elderly,Elderly,0,0,PSS_Magnolia,Human,P,SC,No
3,Sonia,Female,PSS,26,Adult,0,0,PSS_Sonia,Human,P,SC,No
4,Marnie,Female,PSS,Teenager,Teenager,0,0,PSS_Marnie,Human,B,MC,No

In [21]:
# Siguiente dataset...
df_2.head()

,Game_Id,Title,Release,Series,Genre,Sub-genre,Developer,Publisher,Country,Platform,...,Director,Total_team,female_team,Team_percentage,Metacritic,Destructoid,IGN,GameSpot,Avg_Reviews,Unnamed: 27
0,GTAV,Grand Theft Auto V,Nov-13,GTA,Action-adventure,Action-adventure,Rockstar North,Rockstar Games,GBR,Multi,...,M,7,0,0%,9.7,9.0,10.0,9.0,9.4,NaN
1,PSS,Pokémon Sword/Shield,Nov-19,Pokémon,RPG,RPG,Game Freak,Nintendo,JPN,Nintendo Switch,...,M,9,1,11%,8.0,7.0,9.3,9.0,8.3,NaN
2,CODMW,Call of Duty: Modern Warfare,Oct-19,Call of Duty,Action,FPS,Infinity Ward,Activision,USA,Multi,...,M,11,0,0%,8.0,8.0,8.0,7.0,7.8,NaN
3,RDR2,Red Dead Redemption 2,Dec-18,Red Dead,Action-adventure,Action-adventure,Rockstar Studios,Rockstar Games,USA,Multi,...,M,7,0,0%,9.7,9.5,10.0,9.0,9.6,NaN
4,SMO,Super Mario Odyssey,Oct-17,Super Mario,Action-adventure,Action-adventure,Nintendo EDP,Nintendo,JPN,Nintendo Switch,...,M,11,1,9%,9.7,9.5,10.0,10.0,9.8,NaN

In [17]:
# Siguiente dataset...
df_3.head(10)

,Id,Sexualized_clothing,Trophy,Damsel in Distress,Sexualized Cutscenes,Total
0,CODMW_Farah,0,0,0,0,0
1,PSS_Protagonist,0,0,0,0,0
2,PSS_Magnolia,0,0,0,0,0
3,PSS_Sonia,0,0,0,0,0
4,PSS_Marnie,0,0,0,0,0
5,PSS_Oleana,0,0,0,0,0
6,SMO_Peach,0,1,1,0,2
7,BOTW_Zelda,0,0,0,0,0
8,PSM_Protagonist,0,0,0,0,0
9,TW3_Ciri,1,0,1,0,2